# Generated by Django 3.0.9 on 2020-12-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uname',
            field=models.CharField(default='admin', max_length=130),
        ),
    ]
