# Generated by Django 3.2.9 on 2022-03-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211013_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='division',
        ),
        migrations.RemoveField(
            model_name='division',
            name='country',
        ),
        migrations.RemoveField(
            model_name='subdistrict',
            name='district',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='SubDistrict',
        ),
    ]
